<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="">
  <eClassifiers xsi:type="ecore:EClass" name="Hotel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adresse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="etageMin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="etageMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personne" lowerBound="1"
        eType="#//Personne" eOpposite="#//Personne/hotel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chambre" lowerBound="1"
        upperBound="-1" eType="#//Chambre" containment="true" eOpposite="#//Chambre/hotel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chambre">
    <eOperations name="repeindre"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="etage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numero" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbLits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hotel" lowerBound="1" eType="#//Hotel"
        eOpposite="#//Hotel/chambre"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Personne">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hotel" eType="#//Hotel"
        eOpposite="#//Hotel/personne"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SalleDeBain">
    <eOperations name="utiliser"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="etage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numero" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbutilisateurs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Genre">
    <eLiterals name="masculin"/>
    <eLiterals name="feminin" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Couleur"/>
</ecore:EPackage>
